<div class = "customer-data" data-bind="scope: 'section'">
    <h1 data-bind="text: customersection().customername"></h1>
</div>
<script type = "text/x-magento-init">
    {
    "*": {
            "Magento_Ui/js/core/app": {
              "components": {
               "section": {
                  "component": "Gaganashree_Assignment5/js/section"
                  }
               }
            }
         }
    }
 </script>
